name: Python API
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  python_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, windows-2022] # TODO(hlim): Support Mac macos-14, macos-15]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build pip package
        run: |
          python -m pip install --verbose ./python/
      # TODO(hlim) Set unit test
      # - name: Run unittests
      #   run: |
      #     python -m pip install --verbose './python[test]'
      #     pytest -rA --verbose ./python/
